name: pyMassEvac
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - gymnasium
  - pytest
  - pytest-cov
  - tqdm
  - seaborn
