name: gym-mass_evacuation
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - gymnasium
  - stable-baselines3
  - pytest
  - pytest-cov
  - tdqm
  - seaborn
